# Generated by Django 5.0.6 on 2024-05-18 19:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UngDungTimTro', '0004_remove_property_facilities_remove_user_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='images',
            field=models.ImageField(default=None, upload_to='product_images'),
        ),
        migrations.AlterField(
            model_name='image',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_images', to='UngDungTimTro.property'),
        ),
    ]
